# Generated by Django 4.2 on 2023-05-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='quest',
            field=models.ManyToManyField(to='quizApp.question'),
        ),
    ]
