# Generated by Django 4.2 on 2023-05-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0002_report_quest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='quest',
        ),
    ]
