# Generated by Django 4.2 on 2023-05-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0003_remove_report_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='point',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
