# Generated by Django 4.2 on 2023-05-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0006_alter_report_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.TimeField(default="00:05:00" ),
            preserve_default=False,
        ),
    ]
