# Generated by Django 4.2 on 2023-05-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0007_quiz_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
